# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32521f88558ececc09a618b7fbf0120781c88eeda89460e99536fa811a0edd4cc740c1e07bf86b00155377c5f3040c9a66fe791cd828909c655907ad498ac343

test:
  secret_key_base: 04d817209362b42e1ae4165f26a7a4244f4fc7bad3733e0ca754c2b6666d4d7b84e69555e926d1fcca64b60aca3675f1b0c6ab3e0b31ff2773ba8a625310e4c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
